### PR TITLE
Add server.js

### PR DESCRIPTION
**Pull request by kritikawalia10**
Created new branch

### CODE REVIEW

**Comment by kritikawalia10** [comment]
@CodiumAI-Agent/review

**Comment by kritikawalia10** [comment]
@CodiumAI-Agent /review

**Comment by kritikawalia10** [comment]
@CodiumAI-Agent /review

**Comment by th3c0d3br34ker** [comment]
@CodiumAI-Agent /review

**Comment by th3c0d3br34ker** [comment]
@CodiumAI-Agent /describe

**Comment by kritikawalia10** [comment]
@CodiumAI-Agent /review

**Pull request merged**
